version: '3.4'
services:
  mleproject:
    image: dami1ld/mleproject:latest
    network_mode: host
  mleproject_test:
    depends_on:
      - mleproject
    image: dami1ld/mleprojecttest:latest
    network_mode: host
